### ISSUE TITLE
APK can't open file

### ISSUE THREAD

**Issue by kevinnguy** [joshdholtz/fastlane-plugin-s3#16]
After uploading my APK to S3 and downloading it from an Android device, I can't open my apk file and install the app. Here's my Fastfile lane:

```
lane :test do |options|
    gradle(
      task: 'assemble',
      build_type: 'Release',
    )
    aws_s3(
      access_key: ENV['HERO_S3_ACCESS_KEY_STAGING'],
      secret_access_key: ENV['HERO_S3_SECRET_ACCESS_KEY_STAGING'],
      bucket: ENV['HERO_S3_BUCKET_STAGING'],
      region: ENV['HERO_S3_REGION_STAGING'],
      apk: 'app/build/outputs/apk/app-release.apk',
      app_directory: 'test/android',
      upload_metadata: true,
      version_file_name: 'version_android.json',    
    )
end
```

Thanks for the great plugin!

**Comment by kevinnguy** [comment]
I normally distribute my apk via HockeyApp so I assume that my apk isn't corrupted. Here's my lane for that:

```
hockey(
      api_token: ENV['HOCKEY_API'],
      apk: "app/build/outputs/apk/app-release.apk",
      release_type: "3",
      notes: options[:notes]
 )
```

**Comment by joshdholtz** [comment]
@kevinnguy What error are you getting when trying to download/install this?

**Comment by kevinnguy** [comment]
When I try to install my downloaded apk, I get the Android toast `Can't open file`

**Comment by joshdholtz** [comment]
@kevinnguy Are you able to send me the link to the generated HTML page so I can take a closer look? Paste here if you'd like, email to me at me@joshholtz.com, or DM on Twitter at `@joshdhotlz`

**Comment by kevinnguy** [comment]
Sorry @joshdholtz, it's work-related so I can't send you the link. I've ended up using s3cmd to upload my apk manually. This issue may be my own problem so I'll close it.
