### ISSUE TITLE
need plist_file_name option back

### ISSUE THREAD

**Issue by fabware** [joshdholtz/fastlane-plugin-s3#17]
Compare to plugin s3, aws_s3 eliminate plist_file_name option. Without settings plist_file_name, It will makes download link break.

Would like to see it included in a release soon.

**Comment by joshdholtz** [comment]
@fabware Are you referring to #15? This just got merged yesterday and will be releasing today

**Comment by NikKovIos** [comment]
How to update plugin?

**Comment by joshdholtz** [comment]
Version `0.2.3` all pushed to Ruby gems

**Comment by NikKovIos** [comment]
Please write how to update it

**Comment by joshdholtz** [comment]
@NikKovIos It will most likely be 'gem update fastlane-plugin-aws_s3' or `bundle update` depending on how you have things installed... I do not know your setup

**Comment by fabware** [comment]
@joshdholtz thanks for your quick fix.
