### ISSUE TITLE
Custom HTML Template

### ISSUE THREAD

**Issue by cupojoe** [joshdholtz/fastlane-plugin-s3#19]
Is there a way to provide a custom HTML template for the download page?

**Comment by joshdholtz** [comment]
You can use these action params - https://github.com/joshdholtz/fastlane-plugin-s3/blob/master/lib/fastlane/plugin/aws_s3/actions/aws_s3_action.rb#L35-L36

Sorry, documentation on that is not the best right now 😇

**Comment by bdrelling** [comment]
Had this same question, this is great. Thanks!

**Comment by cupojoe** [comment]
Thanks!

**Comment by joshdholtz** [comment]
@bdrelling Had no idea that was a bonus feature 😊 Thanks for even letting me know!

**Comment by cupojoe** [comment]
@joshdholtz Maybe a good default addition would be build number.

**Comment by joshdholtz** [comment]
@cupojoe Where do you want the build number to be added to?  🤔

**Comment by joshdholtz** [comment]
@bdrelling There is not a way to skip the HTML uploading right now but I can add that today!

**Comment by joshdholtz** [comment]
@bdrelling `0.2.7` has your `skip_html_upload` parameter in it

**Comment by cupojoe** [comment]
@joshdholtz I think here:
https://github.com/joshdholtz/fastlane-plugin-s3/blob/master/lib/assets/s3_ios_html_template.erb#L58

**Comment by joshdholtz** [comment]
@cupojoe Ahhhhhh yeah yeah! I can change that today 👌

**Comment by cupojoe** [comment]
@joshdholtz  How would I install the plugin with this changes?

Also, when referencing a custom html_template, running locally it works fine, but when running on bitrise (CI) it doesn't. The path is relative to the root of the project, right?

**Comment by joshdholtz** [comment]
@cupojoe You probably need to run `bundle update` if you are using a `Gemfile`

**Comment by bdrelling** [comment]
@joshdholtz Damn man, you're crushing some work on this in the past few days. Thanks for the support!

**Comment by joshdholtz** [comment]
@bdrelling Thank you, thank you! I've been holding "Fastlane Friday Office Hours" on my Twitch channel (https://www.twitch.tv/joshdholtz) past two Fridays and will try to be every future Friday where I answer anyones questions live and if no one has questions I work on Fastlane PRs so that is why you've been seeing more activity lately 😊  Feel free to drop by my stream on Friday if you need any help with anything!

**Comment by waltermvp** [comment]
@cupojoe did you ever get this working? I am having trouble using `app_directory: "path/to.html.erb"`


and the file looks like so

```
    <!-- app/assets/html/sample.html.erb -->
<!doctype>
<html>
<head>
<%= stylesheet_link_tag "application" %>
</head>

<body>
<p>This is a sample static html page.</p>
</body>

</html>
```

am i missing something?

**Comment by cupojoe** [comment]
@waltermvp did you get it to work?

**Comment by waltermvp** [comment]
@cupojoe yep was missing the       
`html_template_path: 'fastlane/deploy_html_templates/s3_ios_html_template.erb'`

you mentioned. Thanks

**Comment by cupojoe** [comment]
Awesome!
