### ISSUE TITLE
Upload different apps in the same bucket

### ISSUE THREAD

**Issue by mrtj** [joshdholtz/fastlane-plugin-s3#2]
Hi, why "it is highly suggested that you make a separate bucket for each of the apps"? In our company we are maintaining dozens of app releases in a white-label manner so it is rather inconvenient to have a separate bucket just for the release of each of theses apps. Also, AWS accounts have a limit of 100 buckets by default and each app consumes a bucket from this pool shared with other buckets not used for releasing the apps. Instead the number of objects in a bucket is unlimited.

I tried to organize one bucket for all apps configuring the path parameter to include the bundle id: 

```
aws_s3(
    ipa: "artifacts/build/MyApp.ipa",
    path: "{CFBundleIdentifier}/v{CFBundleShortVersionString}_b{CFBundleVersion}/"
)
```

but I noticed that `/index.html` and `/version.json` is overwritten in the root folder of the bucket with the references to the last app uploaded. Is it possible to move these files in the folder specified by `path`?

**Comment by fhickman** [comment]
Agreed, it would be very handy to have an `app_path` configuration variable (which would default to the bucket root), and could be used to organize apps (or branches of apps) under a single S3 bucket.

**Comment by joshdholtz** [comment]
@mrtj I think I had it "highly suggested" because I didn't test it with multiple apps in the same bucket 😬  I can work on adding this feature though - it makes sense and I really don't know why I had it as that in the first place

**Comment by joshdholtz** [comment]
@mrtj @fhickman I just created #11 to add this feature. If either of you would like to review/try the PR before I merge that would be greatly appreciated 😊

**Comment by mrtj** [comment]
Wonderful! I would love to try your PR but being very newbie in ruby/ruby package manager I don't know how could I install a temporary version of aws_s3 plugin from your branch?

**Comment by joshdholtz** [comment]
@mrtj Try changing your `Pluginfile` to following and then run `bundle install`...

```
gem 'fastlane-plugin-s3', git: 'https://github.com/joshdholtz/fastlane-plugin-s3.git', branch: 'app-directory'
```

**Comment by fhickman** [comment]
@joshdholtz I've tried it out locally, works like a charm. You've got my vote for merging it into `master`.

Thanks!

**Comment by n1mda** [comment]
Can you release version 0.2.2 so this is available without pointing the gemfile to a specific branch?

**Comment by joshdholtz** [comment]
@n1mda Should be released now!
