### ISSUE TITLE
AWSFile

### ISSUE THREAD

**Issue by NikKovIos** [joshdholtz/fastlane-plugin-s3#22]
It would be very useful if can use default evironments like Gemfile, Appfile, Matchfile...

**Comment by joshdholtz** [comment]
@NikKovIos You can put your defaults in a `.env` file in the `fastlane` directory

```sh
S3_ACCESS_KEY=<your_access_key>
S3_SECRET_ACCESS_KEY=<your_secret_key>
S3_BUCKET=<your_bucket>
S3_REGION=<your_region>
```

Just run `fastlane action s3` to see all the parameters that have optional environment variables. Using a `.env` file is the preferred method since you can add it to your `.gitignore` so the secrets don't get committed to a repo.

**Comment by joshdholtz** [comment]
Also, let me know if I didn't interpret your question right. I THINK that is what you were getting at but not 100% sure.

**Comment by NikKovIos** [comment]
I have next code
```ruby
aws_s3(
      access_key: ENV["S3_ACCESS_KEY"],
      secret_access_key: ENV["S3_SECRET_ACCESS_KEY"],
      bucket: bucket,
      region: ENV['S3_REGION'],
      ipa: "#{output_directory}/#{ipa_name}",
      dsym: "#{output_directory}/#{dsym_name}",
      path: "",
      upload_metadata: true,
      plist_template_path: "fastlane/s3_plist_template.erb",
      plist_file_name: "manifest.plist",
      html_template_path: "fastlane/s3_html_template.erb",
      html_file_name: "index.html"
      )
```
and i want to put default values to AWSFile due when i use this code it takes values like       `upload_metadata true` or `plist_template_path "fastlane/s3_plist_template.erb"` from it.

**Comment by joshdholtz** [comment]
@NikKovIos I can add this to my list of features to add when I have time... Or I would appreciate a PR if you would like to add this yourself 😊 

I am moving into my new house over the next two weeks so I probably wouldn't get around to this until after then.

**Comment by NikKovIos** [comment]
Good luck)
