### ISSUE TITLE
can't get source param to work

### ISSUE THREAD

**Issue by jpaas** [joshdholtz/fastlane-plugin-s3#23]
I have a React Native app and I'm trying to use the source param to upload my jsbundle and sourcemap along with my ipa and apk files. e.g.

```
aws_s3(
      app_directory: "ios",
      bucket: "mybucket.foo.com",
      region: "us-west-2",
      source: "./build/jsbundle/ios"
    )
```

My ipa, dsym, plist all get uploaded fine, but not the source folder. Is this a bug or am I doing something wrong?

**Comment by joshdholtz** [comment]
@jpaas Not sure if bug and not sure if you are doing something wrong 😊  I have never tried to upload a ReactNative app like this before but I can look into it for you. I am moving into a new house this weekend so I should have some time next week to take a look at this for you 👌

**Comment by jpaas** [comment]
Thanks @joshdholtz. I'm using this plugin to archive my builds. I just wanted to archive the JS code alongside the binary code. From the description of the source param I thought I could throw the JS code and source map into a build folder and it would tag along.

**Comment by joshdholtz** [comment]
@jpaas This is released in `0.2.6` now ✊  Thanks for reporting this!

**Comment by jpaas** [comment]
Thanks @joshdholtz! It might be a little while before I do my next deploy, but i will be sure to check it out when I do.

**Comment by joshdholtz** [comment]
@jpaas I lied! Please use `0.2.7` 😇  `0.2.6` is 💩
