### ISSUE TITLE
override filename in s3

### ISSUE THREAD

**Issue by oronbz** [joshdholtz/fastlane-plugin-s3#40]
Hi,
I have a specific need to upload the `ipa` to `s3` multiple times and with different names.

I thought it would be nice to add another parameter to the action: `file_name` which will override the default `ipa` param that is currently also being used for the uploaded `file_name`.

I can think of scenarios where this could be relevant for other people as well.
If you're with me on this, I could make a PR for this feature, if not, I'll develop it for local use only.

Let me know what you think or if you need more information regarding this feature.

**Comment by joshdholtz** [comment]
@oronbz Totes down for this option if you want to make a PR 💪

**Comment by oronbz** [comment]
💥  https://github.com/joshdholtz/fastlane-plugin-s3/pull/41

**Comment by oronbz** [comment]
@joshdholtz ping 😸

**Comment by joshdholtz** [comment]
Will be released in next version!
