### ISSUE TITLE
Build time is always 00:00 AM

### ISSUE THREAD

**Issue by acecilia** [joshdholtz/fastlane-plugin-s3#43]
After uploading an IPA, the "build on" is as follows:

`Built on Sat, 28 Oct 2017 00:00 AM`

The date is correct and changes with every build, but the time stays in 00:00 AM every time.
I was looking in your source code, but I can not really follow it. 

Is this a know issue or a problem in my configuration? Where is that build time coming from?
Thanks

**Comment by joshdholtz** [comment]
This is fixed now and will be released in next version!
