### ISSUE TITLE
Trouble with region parameter

### ISSUE THREAD

**Issue by truth3** [joshdholtz/fastlane-plugin-s3#5]
I am having trouble with the region parameter after the action finishes. 

It seems that adding that to the URL for my region causes a cert mismatch (or something) and breaks the download to the device. I can't leave it empty as its a required parameter.

If I trim the `region` from the URL then everything works as expected. FWIW I am in region `us-east-1`. Here is the message the browser shows.

![screen shot 2017-01-23 at 6 36 43 pm](https://cloud.githubusercontent.com/assets/7986768/22227772/fd0b65e6-e19a-11e6-9fbc-64e7fe7f663b.png)

**Comment by joshdholtz** [comment]
@truth3 Hmm, I also use `us-east-1` and I have not had that issue. Can you send me what your code looks like and the output?

**Comment by truth3** [comment]
Here is the action setup (just switched from built-in S3 to the plugin)

```ruby
  aws_s3(
      ipa: ENV['GYM_OUTPUT_NAME'],
      html_file_name: ENV['S3_HTML']
    )
```
And here is the output from the action

```sh
[18:34:50]: `Helper.gem_path` is deprecated. Use the `ROOT` constant from the appropriate tool module instead.
2 - /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-plugin-aws_s3-0.2.0
[18:34:50]: `Helper.gem_path` is deprecated. Use the `ROOT` constant from the appropriate tool module instead.
path /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-plugin-aws_s3-0.2.0/lib/assets/s3_ios_plist_template.erb
[18:34:50]: `Helper.gem_path` is deprecated. Use the `ROOT` constant from the appropriate tool module instead.
path /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-plugin-aws_s3-0.2.0/lib/assets/s3_ios_html_template.erb
[18:34:50]: `Helper.gem_path` is deprecated. Use the `ROOT` constant from the appropriate tool module instead.
path /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-plugin-aws_s3-0.2.0/lib/assets/s3_ios_version_template.erb
[18:34:51]: Successfully uploaded ipa file to

**Comment by truth3** [comment]
I had to get something out the door for a client, and hacked this band-aid together. I just hard coded the **s3_subdomain** in aws_s3_action.rb
      
`s3_subdomain = "s3"`

**Comment by joshdholtz** [comment]
@truth3 It looks like it successfully uploading. Can you try opening that URL in a different browser? (Not sure if that will solve the issue but curious what opening it in Safari/Firefox does)

**Comment by joshdholtz** [comment]
@truth3 I will not be able to look into this tonight but I will work on this tomorrow for ya 👌

**Comment by truth3** [comment]
@joshdholtz No worries.. appreciate the super quick reply. Seems like this might resolve itself? If I accept the warning about the cert and continue, it loads up this error.

<h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p>Ref A: E99C833306984D5896FA8C552AA45E83 Ref B: LAXEDGE0420 Ref C: Mon Jan 23 15:47:15 2017 PST

**Comment by joshdholtz** [comment]
@truth3 Can you try explicitly setting the `region` in your command? Curios if this fixes your issue

```
aws_s3(
      ipa: ENV['GYM_OUTPUT_NAME'],
      region: "us-east-1",
      html_file_name: ENV['S3_HTML']
    )
```

**Comment by truth3** [comment]
@joshdholtz I gave this a try, and same result..  I am wondering if this is just some issue on AWS side as you can compare the different results from the two URLs. The first throws back the error in my previous comment, while the second should give you a proper access denied from AWS.

https://s3-us-east-1.amazonaws.com/iform-ios-build-automation/

https://s3.amazonaws.com/iform-ios-build-automation/

**Comment by joshdholtz** [comment]
@truth3 It seems your URLs being generated are different than how they should be. All of my testing and apps that use this generate the URL in the format of `http://<bucket_name>.s3-<region>.amazonaws.com/android/index.html`.

A url of mine: http://fastlane-plugin-s3.s3-website.us-east-2.amazonaws.com/android/index.html

It _appears_ you may not be using the newest version of the plugin? I **think** I was seeing that same error which is why I made a change into how my URL above is being generated ^

**Comment by truth3** [comment]
@joshdholtz I took a closer look at this, and the plugin version shows 0.2.0 (so should be on latest code). This are the various formats of the URLs created on AWS are shown below. I actually think the one to create the .plist may be outdated as it shows the region before the bucket ( see code in bold).

HTML
`https://<bucket>.s3.amazonaws.com/AppName.html`

PLIST
`https://<region>.amazonaws.com/<bucket>/v8.11.5_b208/AppName.plist`
        **plist_url = "https://#{s3_subdomain}.amazonaws.com/#{s3_bucket}/#{plist_file_name}"**

IPA
`https://<bucket>.s3.amazonaws.com/v8.11.5_b208/AppName.ipa`


Nevertheless, it seems there is still some trouble for me when including region. If I leave it out, and just have **s3** then life is good. Happy to do more research and testing if you have some thoughts.

**Doesn't Work**
https://iform-ios-build-automation.s3-us-east-1.amazonaws.com

**Works**
https://iform-ios-build-automation.s3.amazonaws.com

**Comment by Ogel** [comment]
Hi guys - I was just about to post another issue related to the `us-east-1` region.  When using the plugin, the upload process works fine for us.  However, the installation link on the resulting HTML page is busted.

The `us-east-1` is apparently a rename of the original "standard" region, and for some reason Amazon doesn't support links that reference it directly (like the other regions):
https://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region

Therefore, links like `s3.us-east-1.amazonaws.com` aren't valid - you have to lose the region bit.

The [if/else statement around setting the `s3_subdomain` value](https://github.com/joshdholtz/fastlane-plugin-s3/blob/master/lib/fastlane/plugin/aws_s3/actions/aws_s3_action.rb#L39) looks like it would work for this issue.  However, leaving the `:region` parameter out of the fastlane process causes an error.

@joshdholtz - can you make a fix when you are able?  I don't mind helping with a PR (shouldn't be much code), but thought you might want to handle it in a particular way.  In the meantime, we'll just update the resulting HTML file links by hand.

**Comment by truth3** [comment]
Hey @Ogel if you don't want to edit the HTML by hand, you can modify that one line on the action locally to just strictly use **s3** instead of the region prefix. Thats been working great for me

**Comment by joshdholtz** [comment]
@Ogel Great find! Working on a fix for this now 👌

**Comment by joshdholtz** [comment]
@truth3 Just released version `0.2.1`. My output of the HTML and plist urls can be seen in #9 so this _should_ work for you. The "East" output is using `us-east-1` and the "West" output is using `us-west-1`. I also have a bucket in `us-east-2` which behaves like `us-west-1` does.

I hope this works for you 😊

**Comment by Ogel** [comment]
Thanks for the quick fix, @joshdholtz!  I just upgraded and will use it soon - I'll let you know if we run into any issues.

**Comment by truth3** [comment]
@joshdholtz Just got a chance to upgrade and run a few builds through. Everything is looking 💯  to me. If all looks good to you @Ogel I would say we can close this one and march on.

**Comment by Ogel** [comment]
This ran successfully for me today - thanks!
