### ISSUE TITLE
no implicit conversion of nil into String

### ISSUE THREAD

**Issue by acecilia** [joshdholtz/fastlane-plugin-s3#58]
Updated to 1.4.0 from 1.1.1, I am getting the error "no implicit conversion of nil into String" in the aws_s3 fastlane step. 

I can not provide much more information, since I can not see any more logs in the terminal. For now, I reverted back to version 1.1.1.

**Comment by katunch** [comment]
You have to set the `CFBundleDisplayName` in you `Info.plist`. 
I think the plugin should use `CFBundleName` instead of `CFBundleDisplayName` since this would not automatically be generated by Xcode when you create a project.

**Comment by katunch** [comment]
I Just saw that was an issue which I've reported earlier 😂 so the perfect solving this issue is to use `CFBundleDisplayName` only when it is available. Otherwise use `CFBundleName`

**Comment by acecilia** [comment]
@katunch you mean that to resolve the issue the code in [here](https://github.com/joshdholtz/fastlane-plugin-s3/commit/a0b58076a61857cce8ed3ad665f57e149645c92b) will need to be changed to use CFBundleDisplayName, or CFBundleName in case CFBundleDisplayName is not available?

At the moment I am using fastlane, so the Info.plist file is managed automatically by the lane
