### ISSUE TITLE
How not upload xcarchive.zip and .dSYM.zip?

### ISSUE THREAD

**Issue by lucasromanomr** [joshdholtz/fastlane-plugin-s3#61]
Hello, how do I upload only .ipa and .plist files?

After I upgrade to a new version (1.4), every time I upload the file, it is also uploading `xcarchive.zip`, I think this file is not necessary for my use case. You would have to add a parameter so that it is not sent to s3. Really interesting to `.dSYM`

**Comment by lucasromanomr** [comment]
https://github.com/joshdholtz/fastlane-plugin-s3/pull/60

**Comment by hexelon** [comment]
just put empty string in xcarchive (xcarchive: '')

**Comment by joshdholtz** [comment]
Empty string is the correct solution 😊 Thanks, @hexelon!
