### ISSUE TITLE
Upload files only

### ISSUE THREAD

**Issue by farshadtx** [joshdholtz/fastlane-plugin-s3#65]
Is there a way to ignore all default arguments (like ipa, dsym and xcarchive) and just upload `files`? 

* I know there is another plugin which is suppose to upload files but that one is old and not working.

**Comment by kevnm67** [comment]
@farshadtx have your tried the file or folder properties?

**Comment by farshadtx** [comment]
I'm already using `files` but I still get plist, ipa and dsyms in the bucket.

here is my script:
```
aws_s3(
      bucket: ????,
      region: ????,
      path: "beta/#{version_number}/build-#{build_number}/",
      files: ['build/simulator.zip']
      )
```

**Comment by farshadtx** [comment]
I think the reason was running gym before this call, fixed it by adding empty string to all those args:

```
aws_s3(
      bucket: ????,
      region: ????,
      dsym: '', <-----
      ipa: '', <-----
      xcarchive: '', <-----
      path: "beta/#{version_number}/build-#{build_number}/",
      files: ['build/simulator.zip']
      )
```
