### ISSUE TITLE
ipa_url

### ISSUE THREAD

**Issue by tealorg** [joshdholtz/fastlane-plugin-s3#67]
I want to be able to print ipa_url to file outside the aws_s3 plugin, I see that the env variable has been passed to ipa_url.. How can I print to screen?

**Comment by revolter** [comment]
Does `puts(lane_context[SharedValues::S3_IPA_OUTPUT_PATH])` work?

**Comment by tealorg** [comment]
> Does `puts(lane_context[SharedValues::S3_IPA_OUTPUT_PATH])` work?

Hello Mate,

Thanks I managed to call the environment variable outside aws_s3()

Cheers
